# Site settings
title: Clean Blog
image: img/home-bg.jpg
logo: img/favicon.png
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
author: "Thanh Tran (int3ractive.com)"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username: davidtmiller
facebook_username: IronSummitMedia
gaid: UA-XXXXX-X
disqus_site_id: cleanblogjekyllgithubpages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
safe: false # safe need to be off for local preview
lsi: false
permalink: pretty
paginate: 5
exclude: ["sass","node_modules","Gruntfile.js","package.json","README.md"]
keep_files: []
